Support application key
jfrog/setup-jfrog-cli pull request #232
Opened 2024-12-03 14:05 UTC by SaharBracha

2024-12-03 14:26 UTC, SaharBracha commented
recheck

2024-12-04 08:20 UTC, SaharBracha commented
I have read the CLA Document and I hereby sign the CLA

2024-12-12 17:42 UTC, eyalbe4 requested changes

2024-12-12 17:42 UTC, eyalbe4 commented on lib/utils.js
> +                    console.log('Config file is empty or not found.');
console.log --> console.debug

2024-12-12 17:42 UTC, eyalbe4 commented on lib/utils.js
> +                console.log('Found application key: ' + applicationKey);
console.log --> console.debug

2024-12-12 17:42 UTC, eyalbe4 commented on lib/utils.js
> +                console.log('Error reading config:', error);
console.log --> console.error

2024-12-12 17:42 UTC, eyalbe4 commented on src/utils.ts
> +    private static async getApplicationKey(): Promise<string> {
Let's add a unit test for this function.
See the existing tests as a reference for the testing conventions.

2024-12-15 08:02 UTC, SaharBracha commented on src/utils.ts
> +     * Retrieves the application key from input or .jfrog configuration file.
It's a requirement we got to support both of the options, we can discuss it

2024-12-15 12:54 UTC, eyalbe4 commented on src/utils.ts
> +     * Retrieves the application key from input or .jfrog configuration file.
Let's discuss this requirement, because the use case is unclear to me.

2024-12-17 09:47 UTC, eyalbe4 requested changes

2024-12-17 09:47 UTC, eyalbe4 commented on action.yml
> +        required: false
Why is this input needed?

2024-12-17 09:47 UTC, eyalbe4 commented on src/utils.ts
> +     * If the configuration file does not exist or does not contain the application key, it returns an empty string.
This description is wrong, because the function should only read the application key from the confab file.

2024-12-19 07:15 UTC, merged