Reduce `isHeaderPngAccessible()` timeout
jfrog/setup-jfrog-cli pull request #235
Opened 2024-12-15 14:57 UTC by EyalDelarea

- [ ] All [tests](https://github.com/jfrog/setup-jfrog-cli#build-the-code) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----

2024-12-15 23:08 UTC, hazeltonl approved these changes

2024-12-16 13:54 UTC, ccano2011 approved these changes
This is a much better option, thanks :)

2024-12-26 07:52 UTC, eyalbe4 requested changes

2024-12-26 07:52 UTC, eyalbe4 commented on src/utils.ts
> +     * saves the result in a static variable to avoid multiple checks.
saves --> Saves

2024-12-26 07:52 UTC, eyalbe4 commented on src/utils.ts
> +                socketTimeout: 5000, // Set timeout to 5 seconds
Let's place the comment above the line it describes, and not to the side of it, according to our convention.

2024-12-26 08:05 UTC, merged